# Generated by Django 3.1.7 on 2021-03-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Веб-Технология', 'Web Technology'), ('Компьютердик Графика', 'Computer Graphics'), ('Python ', 'Python'), ('Javascript', 'Javascript'), ('Java', 'Java'), ('Django', 'Django'), ('React', 'React Js'), ('Үйрөнүү техникалары', 'Learning Methods'), ('Илим', 'Science')], default='Веб-Технология', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
